Repository meateam/SpikeServer, pull requests merged in 2021-02, with the labels that each got.

#15 Add option for client management to get all active tokens of client
  .df6284dd55bafba17c0dbb1d5aa8a9f9c4c854bb-audit.json
  src/certs/files/publickeyofclient.pem
  src/client/client.controller.ts
  src/client/client.model.ts
  src/client/client.repository.ts
  src/client/client.router.ts
  src/config.ts
  src/oauth2/oauth2.controller.ts
  src/oauth2/oauth2.parser.ts
  src/scope/scope.repository.ts
Labels: enhancement

#16 Add option to search for dashboard component
  src/client/client.controller.ts
  src/client/client.model.ts
  src/client/client.repository.ts
Labels: feature

#17 Fix dashboard search returned scopes
  src/client/client.controller.ts
  src/client/client.repository.ts
  src/person/person.controller.ts
  src/person/person.router.ts
Labels: fix

#18 Fix get person by id
  package-lock.json
  src/config.ts
  src/person/person.controller.ts
Labels: fix
